config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

   get 'home/about' => 'homes#about'

   get '/search', to: 'searches#search'

  devise_for :users

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end

   resources :users, only: [:show, :edit, :index, :update] do
   resource :relationships, only: [:create, :destroy]
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers' , as: 'followers'
  end

  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
 belongs_to :user
 has_many :book_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 
 def favorited_by?(user)
  favorites.where(user_id: user.id).exists?
 end
 
   validates :title, presence: true
  
   validates :body, presence: true,length: { maximum: 200 }
   
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: 'User'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

  attachment :profile_image

  validates :name, length: {in: 2..20}
  validates :name, uniqueness: true

  validates :introduction, length: { maximum: 50 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   before_action :authenticate_user!,except: [:top, :about]

   before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
     user_path(resource.id)
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

 def create
   @book = Book.find(params[:book_id])
   @comment = current_user.book_comments.new(book_comment_params)
   @comment.book_id = @book.id
   @comment.save
   render :book_comments
   #redirect_to book_path(book)
 end

 def destroy
   @book = Book.find(params[:book_id])
   @comment = BookComment.find(params[:id])
   @comment.destroy
   render :book_comments
   #redirect_to book_path(params[:book_id])
 end

 private

 def book_comment_params
  params.require(:book_comment).permit(:comment)
 end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def new
    @book = Book.new
  end

  def create
   @book = Book.new(book_params)
   @book.user_id = current_user.id
   if @book.save
    flash[:notice] = 'You have created book successfully.'
    redirect_to book_path(@book.id)
   else
     @user = current_user
     @books = Book.all
     render :index
   end
  end

    def index
      @book = Book.new
      @books = Book.all
      @user = current_user
    end

    def show
      @book = Book.find(params[:id])
      @user = @book.user
      @book_new = Book.new
      @comment = BookComment.new
    end

    def edit
    @book = Book.find(params[:id])
     if @book.user == current_user
     render "edit"
     else
     redirect_to books_path
     end
    end

     def update
     @book = Book.find(params[:id])
      if @book.update(book_params)
     flash[:notice] = 'You have updated book successfully.'
     redirect_to book_path(@book.id)
      else
     render :edit
      end
     end

     def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
     end

    private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    #redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    #redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

 def top
 end
 
 def about
 end
 
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :authenticate_user!

  def create
   current_user.follow(params[:user_id])
   redirect_back(fallback_location: root_path)
  end

  def destroy
   current_user.unfollow(params[:user_id])
   redirect_back(fallback_location: root_path)
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

 private

 def search_for(model, content, method)
   if model == 'user'
     if method == 'perfect'
       User.where(name: content)
     else
       User.where('name LIKE ?', '%'+content+'%')
     end
   elsif model == 'book'
    if method == 'perfect'
      Book.where(title: content)
    else
      Book.where('title LIKE ?','%'+content+'%')
    end
   end
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def edit
  @user = User.find(params[:id])
   if @user.id == current_user.id
     render :edit
   else
    redirect_to user_path(current_user.id)
   end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = 'You have updated user successfully.'
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_form.html.erb
<%= form_with(model:[book, comment]) do |f| %>
<%= f.text_area :comment, placeholder: "コメントをここに" %>
<%= f.submit "送信する" %>
<% end %>

app/views/book_comments/_index.html.erb
<% book.book_comments.each do |book_comment| %>
 <tr>
  <td>
   <%= link_to user_path(book.user_id) do %>
    <%= attachment_image_tag book_comment.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
   <% end %>
    <br>
     <%= link_to user_path(book.user.id) do %>
      <%= book_comment.user.name %>
     <% end %>
   </td>
   <td>
    <%= book_comment.comment %>
     </td>
      <% if book_comment.user == current_user %>
     <td>
      <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
      <% end %>
     </td>
     </tr>
  <% end %>

app/views/book_comments/book_comments.js.erb
$("#comments_area").html("<%= j(render 'book_comments/index', book: @book, comment: @comment) %>");
$("textarea").val('');

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
 <thead>
  <tr>
   <th></th>
   <th>Title</th>
   <th>Opinion</th>
   <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
  <tr>
   <td>
    <%= link_to user_path(book.user.id) do %>
    <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg' , fallback: "no_image.jpg" %>
    <% end %>
   </td>
   <td><%= link_to book.title, book_path(book.id) %></td>
   <td><%= book.body %></td>
  </tr>
    <% end %>
    </tbody>
</table>

app/views/books/_list.html.erb
<h2>User info</h2>
 <div class="profile-container">
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <% if user.id == current_user.id %>
  <% end %>
   <table class="table">
    <tbody><tr></tr>
     <tr>
      <th>name</th>
      <th class="profile-name"><%= user.name %></th>
     </tr>
      <tr>
      <th>introduction</th>
      <th class="introduction"><%= user.introduction %></th>
     </tr>
     <tr>
      <th>follows</th>
      <th class="follows"><%= link_to user.followings.count, user_followings_path(user) %>
      </th>
     </tr>
     <tr>
      <th>followers</th>
      <th class="followers"><%= link_to user.followers.count, user_followers_path(user) %></th>
     </tr>
     </tbody>
    </table>
    <% unless current_user == user %>

     <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:"btn btn-info" %>
     <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-success" %>
       <% end %>

      <% else %>
      <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
    <% end %>

 </div>

 <div>
  <h2 class="mt-3">New book</h2>
   <%= form_with model: book, url:'/books', local:true do |f| %>
    <div class="form-group">
     <p>Title</p>
     <%= f.text_field :title, class: "form-control book_title" %>
    </div>
    <div class="form-group">
     <p>Opinion</p>
      <%= f.text_area :body, class: "form-control book_body" %>
    </div>
     <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
     </div>
     <% end %>
 </div>

app/views/books/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1>Editing Book</h1>
    <% if @book.errors.any? %>
     <%= @book.errors.count %>error prohibited this obj from being saved:
      <% @book.errors.full_messages.each do |message| %>
       <%= message %>
     <% end %>
    <% end %>
   <%= form_with model:@book, local:true do |f| %>
    <div class="form-group">
     <p>Title</p>
      <%= f.text_field :title, class: "form-control book_title" %>
    </div>
    <div class="form-group">
     <p>Opinion</p>
      <%= f.text_area :body, class: "form-control book_body" %>
    </div>
    <div class="form-group">
     <%= f.submit 'Update Book', class: "btn btn-success"  %>
    </div>
   <% end %>
    <%= link_to "Show", book_path(@book) %>
     |
    <%= link_to "Back", "/books" %>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
 <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
   <%= message %>
  <% end %>
 <% end %>

 <div class="container">
  <div class="row">
   <div class="col-md-3">
    <%= render 'books/list', user: @user, book: @book %>
   </div>
   <div class="col-md-8 offset-md-1">
    <h1>Books</h1>
     <table class="table table-hover table-inverse">
      <thead>
       <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
       </tr>
      </thead>
       <tbody>
        <% @books.each do |book| %>
         <tr>
          <td>
           <%= link_to user_path(book.user.id) do %>
            <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg' , fallback: "no_image.jpg" %>
           <% end %>
          </td>
           <td>
            <%= link_to book.title, book_path(book.id) %>
           </td>
           <td>
            <%= book.body %>
           </td>
            <%# if book.favorited_by?(current_user) %>
             <td id="favorite_buttons_<%= book.id %>">
           <%= render "favorites/favorites", book: book %>
              <%#= link_to book_favorites_path(book.id), method: :delete, remote: true do %>
               <%#= book.favorites.count %>
             <%# end %>
             <!--</td>-->
             <%# else %>
             <!--<td>-->
              <%#= link_to book_favorites_path(book.id), method: :book, remote: true do %>
               <%#= book.favorites.count %>
              <%# end %>
             </td>
             <%# end %>
           <td>
            コメント件数:<%= book.book_comments.count %>
           </td>
          </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>
 </div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
     <%= render 'books/list', user: @user, book: @book_new %>
    </div>
     <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
       <table class="table">
        <tbody>
         <tr>
          <td>
           <%=link_to user_path(@book.user_id) do %>
            <%= attachment_image_tag @user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
           <% end %>
           <br>
            <%=link_to user_path(@user.id) do %>
             <%= @user.name %>
            <% end %>
           </td>
            <td>
             <%=link_to @book.title %>
            </td>
             <td>
              <%= @book.body %>
             </td>
             <td id="favorite_buttons_<%= @book.id %>">
           　<%= render "favorites/favorites", book: @book %>
             </td>
             <td>
              コメント件数:<%= @book.book_comments.count %>
             </td>
              <% if @book.user_id == current_user.id %>
               <td>
              <%= link_to "Edit", edit_book_path(@book.id),class: "btn btn-sm btn-success" %>
               </td>
                <td>
                 <%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %>
                </td>
               <% end %>
            </tr>
             </div>
            </tbody>
           </table>
           <table id="comments_area">
            <%= render 'book_comments/index', book: @book %>
           </table>
            <div class="new-comment">
             <%= render 'book_comments/form', book: @book, comment: @comment %>
            </div>
      </div>
  </div>
</div>

app/views/favorites/_favorites.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
  ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
  ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
         <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
         <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
<table class="table table-hover table-inverse">
<thead>
  <tr>
    <th>image</th>
    <th>name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
     <tr>
      <td>
       <%= attachment_image_tag user, :profile_image, :fill,40,40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
      </td>
      <td><%= user.name %></td>
      <td>フォロー数: <%= user.followings. count %></td>
      <td>フォロワー数:<%= user.followers.count %></td>
      <td>
      <%= link_to 'Show', user_path(user.id) %>
      </td>
     </tr>
     <% end %>
  </tbody>
  </table>
  <% else %>
  <p>ユーザはいません</p>
  <% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
<table class="table table-hover table-inverse">
<thead>
  <tr>
    <th>image</th>
    <th>name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
     <tr>
      <td>
       <%= attachment_image_tag user, :profile_image, :fill,40,40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
      </td>
      <td><%= user.name %></td>
      <td>フォロー数: <%= user.followings. count %></td>
      <td>フォロワー数:<%= user.followers.count %></td>
      <td>
      <%= link_to 'Show', user_path(user.id) %>
      </td>
     </tr>
     <% end %>
  </tbody>
  </table>
  <% else %>
  <p>ユーザはいません</p>
  <% end %>

app/views/searches/_form.html.erb
<% if user_signed_in? %>
 <%= form_tag(search_path, method: :get) do %>
  <%= text_field_tag 'content'%>
  <%= select_tag 'model', options_for_select({"User" => "user", "Book" => "book"}) %>
  <%= select_tag 'method', options_for_select({"完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"}) %>
  <%= submit_tag '検索' %>
 <% end %>
<% end %>

app/views/searches/search.html.erb
<% if @model == 'user' %>
 <h3>Users search for "<%= @content %>"</h3>
 <%= render 'users/index', users: @records %>
<% else @model == 'books' %>
 <h3>Books search for "<%= @content %>"</h3>
 <%= render 'books/index', books: @records %>
 <% end %>

app/views/users/_index.html.erb
<table class="table">
       <thead>
        <tr>
         <th>image</th>
         <th>name</th>
         <th colspan="3"></th>
        </tr>
       </thead>
      <tbody>
  <% users.each do |user| %>
  <tr>
   <td>
   <%= attachment_image_tag user, :profile_image, :fill,40,40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
   </td>
   <td>
  <%= link_to user_path(user) do %>
    <%= user.name %>
  <% end %>
  </td>
  </tr>
<% end %>
</tbody>
</table>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
       <div class="form-group">
        <label for="inputName">Name</label>
         <%= f.text_field :name, autofocus: true, id:"inputName", class: "form-control" %>
       </div>
       <div class="form-group">
        <label for="inputImage">Image</label>
         <%= f.attachment_field :profile_image, class: "form-control-file" %>
       </div>
       <div class="form-group">
        <lavel for="inputIntrodution">Introdution</lavel>
         <%= f.text_area :introduction, autofocus: true, id:"introduction", class: "form-control" %>
      </div>
      <div class="form-group">
       <%= f.submit "Update User", class: "btn btn-secondary" %>
      </div>
    <% end %>
    </div>
   </div>
  </div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
     <%= render 'books/list', user: @user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
     <h2>Users</h2>
      <table class="table">
       <thead>
        <tr>
         <th>image</th>
         <th>name</th>
         <th colspan="3"></th>
        </tr>
       </thead>
      <tbody>
       <% @users.each do |user| %>
        <tr>
          <td>
           <%= attachment_image_tag user, :profile_image, :fill,40,40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
          </td>
          <td>
           <%= user.name %>
          </td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><% unless current_user == user %>
          <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
          <% end %>
          </td>
          <td>
           <%= link_to 'Show', user_path(user.id) %>
          </td>
         </tr>
        <% end %>
      </tbody>
     </table>
    </div>
   </div>
 </div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', book: @book, user: @user %>
    </div>
     <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
       <table class="table table-hover table-inverse">
         <thead>
          <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th colspan="3"></th>
          </tr>
         </thead>
       <tbody>
        <% @books.each do |book| %>
         <tr>
          <td>
           <%=link_to user_path(book.user_id) do %>
            <%= attachment_image_tag @user, :profile_image, size: "40x40", format: 'jpeg' , fallback: "no_image.jpg" %>
           <% end %>
          </td>
          <td>
           <%= link_to book.title, book_path(book.id) %>
          </td>
          <td>
           <%= book.body %>
          </td>
          <td>
          コメント件数:<%= book.book_comments.count %>
          </td>
         </tr>
        <% end %>
       </tbody>
     </table>
   </div>
  </div>
</div>