config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

   get 'home/about' => 'homes#about'

   get '/search', to: 'searches#search'

  devise_for :users

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end

   resources :users, only: [:show, :edit, :index, :update] do
   resource :relationships, only: [:create, :destroy]
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers' , as: 'followers'
  end

  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
 belongs_to :user
 has_many :book_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 
 def favorited_by?(user)
  favorites.where(user_id: user.id).exists?
 end
 
   validates :title, presence: true
  
   validates :body, presence: true,length: { maximum: 200 }
   
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: 'User'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

  attachment :profile_image

  validates :name, length: {in: 2..20}
  validates :name, uniqueness: true

  validates :introduction, length: { maximum: 50 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   before_action :authenticate_user!,except: [:top, :about]

   before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
     user_path(resource.id)
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def new
    @book = Book.new
  end

  def create
   @book = Book.new(book_params)
   @book.user_id = current_user.id
   if @book.save
    flash[:notice] = 'You have created book successfully.'
    redirect_to book_path(@book.id)
   else
     @user = current_user
     @books = Book.all
     render :index
   end
  end

    def index
      @book = Book.new
      @books = Book.all
      @user = current_user
    end

    def show
      @book = Book.find(params[:id])
      @user = @book.user
      @book_new = Book.new
      @comment = BookComment.new
    end

    def edit
    @book = Book.find(params[:id])
     if @book.user == current_user
     render "edit"
     else
     redirect_to books_path
     end
    end

     def update
     @book = Book.find(params[:id])
      if @book.update(book_params)
     flash[:notice] = 'You have updated book successfully.'
     redirect_to book_path(@book.id)
      else
     render :edit
      end
     end

     def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
     end

    private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    #redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    #redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

 def top
 end
 
 def about
 end
 
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

 private

 def search_for(model, content, method)
   if model == 'user'
     if method == 'perfect'
       User.where(name: content)
     else
       User.where('name LIKE ?', '%'+content+'%')
     end
   elsif model == 'book'
    if method == 'perfect'
      Book.where(title: content)
    else
      Book.where('title LIKE ?','%'+content+'%')
    end
   end
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def edit
  @user = User.find(params[:id])
   if @user.id == current_user.id
     render :edit
   else
    redirect_to user_path(current_user.id)
   end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = 'You have updated user successfully.'
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
  <head>
    <title>Bookers</title>
     <%= csrf_meta_tags %>
     <%= csp_meta_tag %>
      <script src="https://kit.fontawesome.com/37a1a86a06.js" crossorigin="anonymous"></script>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
    <nav class="navbar navbar-expend-lg navbar-dark bg-dark" >
     <div class="container">
      <%= link_to "Bookers", root_path, class: "navbar-brand" %>
      <!--<div class="collapse navbar-collapse">-->
      <ul class="list-group-horizontal navbar-nav ml-auto">
       <% if user_signed_in? %>
        <li class="margin-right">
         <%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
        </li>
        <li class="margin-right">
         <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
        </li>
        <li class="margin-right">
         <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
        </li>
         <li class="margin-right">
          <%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
         </li>
        <% else %>
         <li class="margin-right">
           <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
         </li>
         <li class="margin-right">
          <%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light" %>
         </li>
         <li class="margin-right">
          <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
         </li>
         <li class="margin-right">
          <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
         </li>
        <% end %>
       </ul>
      </div>
     </nav>
     <div class="d-flex justify-content-center">
      <%= render 'searches/form' %>
     </div>
    </header>

     <main>
       <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
       <% end %>
      <%= yield %>
     </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>